#!/bin/sh
# Builds dist/<Style>.css from src/_core.css plus each src/<style>.css.
set -e
cd "$(dirname "$0")"
mkdir -p dist

for theme in src/[!_]*.css; do
    base=$(basename "$theme" .css)
    name="$(printf '%s' "$base" | cut -c1 | tr '[:lower:]' '[:upper:]')$(printf '%s' "$base" | cut -c2-)"
    {
        printf '/*\nTitle: %s\nAuthor: Phillip Rearick\nGenerated by build.sh from src/_core.css and %s. Edit those, not this file.\n*/\n\n' "$name" "$theme"
        cat src/_core.css
        printf '\n'
        cat "$theme"
    } > "dist/$name.css"
    echo "dist/$name.css"
done
